apiVersion: v1
kind: Service
metadata:
  name: fo3-grafana
  namespace: fo3-wallet
  labels:
    app.kubernetes.io/name: fo3-grafana
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grafana
  selector:
    app.kubernetes.io/name: fo3-grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fo3-grafana-pvc
  namespace: fo3-wallet
  labels:
    app.kubernetes.io/name: fo3-grafana
    app.kubernetes.io/component: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fo3-grafana
  namespace: fo3-wallet
  labels:
    app.kubernetes.io/name: fo3-grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/version: "10.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fo3-grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fo3-grafana
        app.kubernetes.io/component: monitoring
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 472
        fsGroup: 472
      containers:
      - name: grafana
        image: grafana/grafana:10.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: grafana
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fo3-monitoring-secret
              key: GRAFANA_PASSWORD
        - name: GF_USERS_ALLOW_SIGN_UP
          value: "false"
        - name: GF_SECURITY_DISABLE_GRAVATAR
          value: "true"
        - name: GF_ANALYTICS_REPORTING_ENABLED
          value: "false"
        - name: GF_ANALYTICS_CHECK_FOR_UPDATES
          value: "false"
        - name: GF_INSTALL_PLUGINS
          value: "grafana-piechart-panel,grafana-worldmap-panel,grafana-clock-panel,grafana-simple-json-datasource"
        - name: GF_SERVER_ROOT_URL
          value: "https://grafana.fo3wallet.com"
        - name: GF_SERVER_SERVE_FROM_SUB_PATH
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"
        - name: GF_AUTH_BASIC_ENABLED
          value: "true"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "false"
        - name: GF_SMTP_ENABLED
          value: "true"
        - name: GF_SMTP_HOST
          value: "smtp.fo3wallet.com:587"
        - name: GF_SMTP_FROM_ADDRESS
          value: "alerts@fo3wallet.com"
        - name: GF_SMTP_FROM_NAME
          value: "FO3 Wallet Monitoring"
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        - name: grafana-config
          mountPath: /etc/grafana/grafana.ini
          subPath: grafana.ini
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards-config
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1
            memory: 2Gi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: fo3-grafana-pvc
      - name: grafana-config
        configMap:
          name: fo3-grafana-config
      - name: grafana-datasources
        configMap:
          name: fo3-grafana-datasources
      - name: grafana-dashboards-config
        configMap:
          name: fo3-grafana-dashboards-config
      - name: grafana-dashboards
        configMap:
          name: fo3-grafana-dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fo3-grafana-config
  namespace: fo3-wallet
  labels:
    app.kubernetes.io/name: fo3-grafana
    app.kubernetes.io/component: monitoring
data:
  grafana.ini: |
    [analytics]
    check_for_updates = false
    reporting_enabled = false

    [grafana_net]
    url = https://grafana.net

    [log]
    mode = console
    level = info

    [paths]
    data = /var/lib/grafana/data
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]
    protocol = http
    http_port = 3000
    domain = grafana.fo3wallet.com
    enforce_domain = false
    root_url = https://grafana.fo3wallet.com
    serve_from_sub_path = true

    [database]
    type = sqlite3
    host = 127.0.0.1:3306
    name = grafana
    user = root
    password =
    url =
    ssl_mode = disable
    path = grafana.db
    max_idle_conn = 2
    max_open_conn =
    conn_max_lifetime = 14400
    log_queries =

    [session]
    provider = file
    provider_config = sessions
    cookie_name = grafana_sess
    cookie_secure = true
    session_life_time = 86400

    [dataproxy]
    logging = false
    timeout = 30
    send_user_header = false

    [security]
    admin_user = admin
    admin_password = $__env{GF_SECURITY_ADMIN_PASSWORD}
    secret_key = SW2YcwTIb9zpOOhoPsMm
    login_remember_days = 7
    cookie_username = grafana_user
    cookie_remember_name = grafana_remember
    disable_gravatar = true
    allow_embedding = false
    strict_transport_security = true
    strict_transport_security_max_age_seconds = 86400
    strict_transport_security_preload = false
    strict_transport_security_subdomains = false
    x_content_type_options = true
    x_xss_protection = true

    [snapshots]
    external_enabled = false

    [dashboards]
    versions_to_keep = 20

    [users]
    allow_sign_up = false
    allow_org_create = false
    auto_assign_org = true
    auto_assign_org_id = 1
    auto_assign_org_role = Viewer
    verify_email_enabled = false
    login_hint = email or username
    default_theme = dark

    [auth]
    login_cookie_name = grafana_session
    login_maximum_inactive_lifetime_duration = 7d
    login_maximum_lifetime_duration = 30d
    token_rotation_interval_minutes = 10
    disable_login_form = false
    disable_signout_menu = false
    signout_redirect_url =
    oauth_auto_login = false

    [auth.anonymous]
    enabled = false

    [auth.basic]
    enabled = true

    [smtp]
    enabled = true
    host = smtp.fo3wallet.com:587
    user = alerts@fo3wallet.com
    password = $__env{GF_SMTP_PASSWORD}
    cert_file =
    key_file =
    skip_verify = false
    from_address = alerts@fo3wallet.com
    from_name = FO3 Wallet Monitoring
    ehlo_identity = grafana.fo3wallet.com

    [emails]
    welcome_email_on_sign_up = false
    templates_pattern = emails/*.html

    [log]
    mode = console
    level = info
    filters = rendering:debug

    [log.console]
    level = info
    format = console

    [alerting]
    enabled = true
    execute_alerts = true
    error_or_timeout = alerting
    nodata_or_nullvalues = no_data
    concurrent_render_limit = 5

    [metrics]
    enabled = true
    interval_seconds = 10

    [metrics.graphite]
    address =
    prefix = prod.grafana.%(instance_name)s.

    [tracing.jaeger]
    address = fo3-jaeger:14268
    always_included_tag = tag1:value1
    sampler_type = const
    sampler_param = 1

    [external_image_storage]
    provider = local

    [external_image_storage.local]
    path = data/png

    [rendering]
    server_url =
    callback_url =
    concurrent_render_request_limit = 30

    [panels]
    enable_alpha = false
    disable_sanitize_html = false

    [plugins]
    enable_alpha = false
    app_tls_skip_verify_insecure = false

    [enterprise]
    license_path =

    [feature_toggles]
    enable = 

    [date_formats]
    full_date = MMM Do, YYYY
    interval_second = HH:mm:ss
    interval_minute = HH:mm
    interval_hour = MM/DD HH:mm
    interval_day = MM/DD
    interval_month = YYYY-MM
    interval_year = YYYY
    use_browser_locale = false
    default_timezone = UTC
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fo3-grafana-datasources
  namespace: fo3-wallet
  labels:
    app.kubernetes.io/name: fo3-grafana
    app.kubernetes.io/component: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://fo3-prometheus:9090
      isDefault: true
      editable: true
      jsonData:
        timeInterval: 15s
        queryTimeout: 60s
        httpMethod: POST
        manageAlerts: true
        prometheusType: Prometheus
        prometheusVersion: 2.45.0
        cacheLevel: 'High'
        incrementalQuerying: true
        incrementalQueryOverlapWindow: 10m
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://fo3-jaeger:16686
      editable: true
      jsonData:
        tracesToLogs:
          datasourceUid: 'loki'
          tags: ['job', 'instance', 'pod', 'namespace']
          mappedTags: [{ key: 'service.name', value: 'service' }]
          mapTagNamesEnabled: false
          spanStartTimeShift: '1h'
          spanEndTimeShift: '1h'
          filterByTraceID: false
          filterBySpanID: false
        nodeGraph:
          enabled: true
        spanBar:
          type: 'Tag'
          tag: 'http.path'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fo3-grafana-dashboards-config
  namespace: fo3-wallet
  labels:
    app.kubernetes.io/name: fo3-grafana
    app.kubernetes.io/component: monitoring
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
    - name: 'fo3-wallet-dashboards'
      orgId: 1
      folder: 'FO3 Wallet'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards
