# FO3 Wallet Core Production Configuration
# Phase 5B - ML Infrastructure and Automated Trading

[server]
host = "0.0.0.0"
grpc_port = 50051
http_port = 8080
metrics_port = 9090
max_connections = 1000
request_timeout_seconds = 30
keep_alive_seconds = 60
tcp_nodelay = true
tcp_keepalive = true

[database]
url = "${DATABASE_URL}"
pool_size = 20
connection_timeout_seconds = 30
idle_timeout_seconds = 600
max_lifetime_seconds = 3600
statement_timeout_seconds = 60
enable_ssl = true
ssl_mode = "require"
enable_query_logging = true
auto_migrate = true
enable_user_isolation = true

[redis]
url = "${REDIS_URL}"
pool_size = 10
connection_timeout_seconds = 5
command_timeout_seconds = 3
retry_attempts = 3
retry_delay_ms = 100
enable_cluster = false
enable_ssl = true

[security]
jwt_secret = "${JWT_SECRET}"
jwt_expiry_seconds = 3600
jwt_refresh_expiry_seconds = 86400
bcrypt_cost = 12
rate_limit_enabled = true
audit_enabled = true
encryption_key = "${ENCRYPTION_KEY}"
session_timeout_seconds = 1800
enable_user_isolation = true
enforce_rbac = true
audit_all_operations = true

[rate_limiting]
default_requests_per_minute = 100
burst_size = 150
trading_requests_per_hour = 500
ml_requests_per_minute = 50
auth_requests_per_minute = 20
cleanup_interval_seconds = 300

[ml]
models_path = "/app/models"
cache_size_mb = 512
batch_size = 32
inference_timeout_ms = 5000
worker_threads = 2
enable_gpu = false
model_warming = true
quantization_enabled = true

[ml.models]
sentiment_analyzer = "sentiment_model.bin"
yield_predictor = "yield_predictor.bin"
market_predictor = "market_predictor.bin"
risk_assessor = "risk_assessor.bin"
trading_signals = "trading_signals.bin"

[trading]
risk_checks_enabled = true
circuit_breaker_enabled = true
max_positions_per_user = 100
max_daily_trades_per_user = 1000
position_size_limit_usd = 1000000
portfolio_risk_limit = 0.2
leverage_limit = 10.0
stop_loss_required = true
fraud_detection_enabled = true

[trading.risk_management]
var_confidence_level = 0.95
max_drawdown_limit = 0.15
correlation_limit = 0.8
concentration_limit = 0.3
liquidity_threshold = 0.1
stress_test_enabled = true

[automated_trading]
max_strategies_per_user = 10
strategy_timeout_seconds = 300
rebalance_frequency_minutes = 60
signal_expiry_minutes = 30
execution_slippage_limit = 0.005
min_trade_amount_usd = 10.0
max_trade_amount_usd = 100000.0

[pricing]
cache_ttl_seconds = 30
price_deviation_threshold = 0.05
historical_data_retention_days = 365
real_time_updates = true
fallback_providers = ["coingecko", "coinmarketcap"]
update_interval_seconds = 5

[notifications]
websocket_enabled = true
push_notifications_enabled = true
email_notifications_enabled = true
sms_notifications_enabled = false
max_connections_per_user = 5
heartbeat_interval_seconds = 30
message_queue_size = 1000

[kyc]
document_storage_path = "/app/data/kyc"
verification_timeout_hours = 72
max_document_size_mb = 10
allowed_document_types = ["pdf", "jpg", "jpeg", "png"]
encryption_enabled = true
audit_trail_enabled = true

[wallet]
default_currency = "USD"
supported_currencies = ["USD", "EUR", "GBP", "BTC", "ETH", "USDC", "USDT"]
transaction_timeout_seconds = 300
confirmation_blocks = 6
gas_price_multiplier = 1.2
max_gas_limit = 500000

[card]
virtual_cards_enabled = true
physical_cards_enabled = false
daily_spending_limit_usd = 5000
monthly_spending_limit_usd = 50000
international_transactions = true
contactless_enabled = true
pin_required = true

[fiat_gateway]
supported_methods = ["bank_transfer", "card", "ach"]
min_deposit_usd = 10.0
max_deposit_usd = 50000.0
min_withdrawal_usd = 10.0
max_withdrawal_usd = 25000.0
processing_timeout_seconds = 600
fee_percentage = 0.015

[audit]
enabled = true
log_level = "info"
retention_days = 2555  # 7 years for compliance
encryption_enabled = true
real_time_monitoring = true
alert_on_suspicious_activity = true
export_format = "json"

[monitoring]
metrics_enabled = true
tracing_enabled = true
health_check_interval_seconds = 30
performance_monitoring = true
error_tracking = true
log_sampling_rate = 1.0

[monitoring.prometheus]
enabled = true
port = 9090
path = "/metrics"
include_system_metrics = true
include_business_metrics = true

[monitoring.jaeger]
enabled = true
agent_endpoint = "${JAEGER_AGENT_ENDPOINT}"
service_name = "fo3-wallet-core"
sampling_rate = 0.1

[logging]
level = "info"
format = "json"
output = "stdout"
file_rotation = true
max_file_size_mb = 100
max_files = 10
include_caller = true
include_timestamp = true

[performance]
worker_threads = 8
blocking_threads = 16
max_blocking_threads = 512
thread_stack_size = 2097152  # 2MB
thread_keep_alive_seconds = 10
enable_io_uring = false

[cache]
default_ttl_seconds = 300
max_entries = 100000
eviction_policy = "lru"
compression_enabled = true
encryption_enabled = false

[feature_flags]
ml_inference = true
automated_trading = true
advanced_analytics = true
real_time_notifications = true
multi_chain_support = true
defi_integrations = true
yield_farming = true
arbitrage_detection = true
sentiment_analysis = true
market_prediction = true

[compliance]
gdpr_enabled = true
ccpa_enabled = true
sox_compliance = true
pci_dss_compliance = true
aml_enabled = true
kyc_required = true
data_retention_days = 2555
right_to_be_forgotten = true

[backup]
enabled = true
interval_hours = 6
retention_days = 30
encryption_enabled = true
compression_enabled = true
remote_storage = true
verification_enabled = true

[disaster_recovery]
enabled = true
rpo_minutes = 15  # Recovery Point Objective
rto_minutes = 60  # Recovery Time Objective
backup_regions = ["us-west-2", "eu-west-1"]
failover_enabled = true
health_check_enabled = true

[development]
debug_mode = false
hot_reload = false
mock_external_services = false
test_mode = false
profiling_enabled = false

[external_services]
coingecko_api_key = "${COINGECKO_API_KEY}"
coinmarketcap_api_key = "${COINMARKETCAP_API_KEY}"
sendgrid_api_key = "${SENDGRID_API_KEY}"
twilio_api_key = "${TWILIO_API_KEY}"
aws_access_key = "${AWS_ACCESS_KEY_ID}"
aws_secret_key = "${AWS_SECRET_ACCESS_KEY}"
aws_region = "${AWS_REGION}"

[blockchain]
ethereum_rpc_url = "${ETHEREUM_RPC_URL}"
polygon_rpc_url = "${POLYGON_RPC_URL}"
bsc_rpc_url = "${BSC_RPC_URL}"
solana_rpc_url = "${SOLANA_RPC_URL}"
arbitrum_rpc_url = "${ARBITRUM_RPC_URL}"
optimism_rpc_url = "${OPTIMISM_RPC_URL}"

[defi]
uniswap_v3_enabled = true
aave_enabled = true
compound_enabled = true
curve_enabled = true
yearn_enabled = true
convex_enabled = true
max_slippage = 0.005
gas_optimization = true
