name: fo3_wallet_sdk
description: Official Flutter SDK for FO3 Wallet Core - Comprehensive DeFi infrastructure with enterprise-grade security
version: 3.0.0
homepage: https://fo3wallet.com
repository: https://github.com/bankchen1/fo3-wallet-core
documentation: https://docs.fo3wallet.com/flutter-sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # gRPC and Protocol Buffers
  grpc: ^3.2.4
  protobuf: ^3.1.0
  fixnum: ^1.1.0
  
  # WebSocket and Real-time Communication
  web_socket_channel: ^2.4.0
  
  # Storage and Caching
  shared_preferences: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Network and Connectivity
  dio: ^5.3.0
  connectivity_plus: ^4.0.2
  
  # Cryptography and Security
  crypto: ^3.0.3
  encrypt: ^5.0.1
  
  # Utilities
  uuid: ^3.0.7
  intl: ^0.18.1
  
  # State Management (Optional - for examples)
  provider: ^6.0.5
  
  # Logging and Analytics
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  hive_generator: ^2.0.0
  
  # Testing
  mockito: ^5.4.2
  test: ^1.24.6
  integration_test:
    sdk: flutter

# Code Generation
flutter:
  # No assets needed for SDK

# Build Configuration
build_runner:
  targets:
    $default:
      builders:
        hive_generator:hive_generator:
          options:
            # Hive code generation options

# Documentation
topics:
  - defi
  - blockchain
  - wallet
  - grpc
  - flutter
  - sdk
  - cryptocurrency
  - yield-farming
  - trading

# Funding
funding:
  - https://github.com/sponsors/fo3wallet

# Screenshots (for pub.dev)
screenshots:
  - description: 'FO3 Wallet SDK Integration Example'
    path: screenshots/integration_example.png
  - description: 'Real-time Market Data'
    path: screenshots/market_data.png
  - description: 'Yield Farming Dashboard'
    path: screenshots/yield_farming.png

# Platforms
platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:
